services:
  deploy.hook.queuing:
    class: Crocos\Plugin\DeployPlugin\Hook\QueuingHook
    arguments:
      - @release.queue
      - @release.branch_matcher
      - @release.flow_resolver

  deploy.hook.releaselog:
    class: Crocos\Plugin\DeployPlugin\Hook\ReleaseLogHook
    arguments:
      - @releaselog.logger
      - @releaselog.notifier
      - @releaselog.branch_matcher

  shell:
    class: Crocos\Plugin\DeployPlugin\Shell


  # release
  release.flow_resolver_factory:
    class: Crocos\Plugin\DeployPlugin\Release\FlowResolverFactory
    arguments:
      - %release.flow%

  release.flow_resolver:
    class: Crocos\Plugin\DeployPlugin\Release\FlowResolver
    factory_service: release.flow_resolver_factory
    factory_method: create

  release.controller:
    class: Crocos\Plugin\DeployPlugin\Release\ReleaseController
    arguments:
      - @release.queue
      - @release.command_context
      - @shell
      - @release.branch_matcher
      - @release.flow_resolver
      - @logger

  release.queue:
    alias: release.file_queue

  release.file_queue:
    class: Crocos\Plugin\DeployPlugin\Release\FileQueue
    arguments:
      - %queue.dir%

  release.command_context:
    class: Crocos\Plugin\DeployPlugin\Release\CommandContext
    calls:
      - [ setEnv, [ %release.command_context.env% ] ]

  release.command_resolver:
    class: Crocos\Plugin\DeployPlugin\Release\CommandResolver
    arguments:
      - @release.command_context
      - @shell
      - @service_container
      - @logger

  release.command.anchor:
    class: Crocos\Plugin\DeployPlugin\Release\Command\AnchorCommand
    arguments:
      - %release.lockfile%

  release.command.sail:
    class: Crocos\Plugin\DeployPlugin\Release\Command\SailCommand
    arguments:
      - %release.lockfile%

  release.command.watch:
    class: Crocos\Plugin\DeployPlugin\Release\Command\WatchCommand
    arguments:
      - %release.lockfile%

  release.worker:
    class: Crocos\Plugin\DeployPlugin\Release\Worker
    arguments:
      - @release.queue
      - @release.controller
      - @logger

  release.branch_matcher:
    class: Navy\BranchMatcher
    arguments:
      - %deploy.repository%


  # releaselog
  releaselog.logger:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\Logger
    arguments:
      - @releaselog.logfile
      - @releaselog.period
      - @releaselog.markdown_scraper

  releaselog.logfile:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\LogFile
    arguments:
      - %releaselog.logfile.config%

  releaselog.period:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\Period
    arguments:
      - ~

  releaselog.notifier:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\Notifier
    arguments:
      - @releaselog.markdown_scraper
      - %releaselog.notifier.hipchat.rooms%
      - %releaselog.notifier.pullrequest.topics%
      - %releaselog.notifier.hipchat.token%
      - %releaselog.notifier.hipchat.name%
      - %releaselog.pullrequest.labels.mapping%
      - %releaselog.pullrequest.username.command%

  releaselog.reader:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\Reader
    arguments:
      - @releaselog.logfile
      - @releaselog.period

  releaselog.markdown_scraper:
    class: Crocos\Plugin\DeployPlugin\ReleaseLog\MarkdownScraper

  releaselog.branch_matcher:
    class: Navy\BranchMatcher
    arguments:
      - %releaselog.hook.repository%
