services:
  deploy.hook.queuing:
    class: Crocos\Navy\DeployPlugin\Hook\QueuingHook
    arguments:
      - @release.queue
      - @release.branch_matcher
      - @release.flow_resolver

  deploy.hook.releaselog:
    class: Crocos\Navy\DeployPlugin\Hook\ReleaseLogHook
    arguments:
      - @releaselog.logger
      - @releaselog.notifier
      - @releaselog.branch_matcher

  shell:
    class: Crocos\Navy\DeployPlugin\Shell


  # release
  release.branch_matcher:
    class: Navy\BranchMatcher
    arguments:
      - %deploy.release.repository%

  release.flow_resolver_factory:
    class: Crocos\Navy\DeployPlugin\Release\FlowResolverFactory
    arguments:
      - %deploy.release.flow%

  release.flow_resolver:
    class: Crocos\Navy\DeployPlugin\Release\FlowResolver
    factory_service: release.flow_resolver_factory
    factory_method: create

  release.controller:
    class: Crocos\Navy\DeployPlugin\Release\ReleaseController
    arguments:
      - @release.queue
      - @release.command_context
      - @shell
      - @release.branch_matcher
      - @release.flow_resolver
      - @notifier
      - @logger

  release.queue:
    class: Crocos\Navy\DeployPlugin\Release\QueueInterface
    factory_service: release.queue_provider
    factory_method: get

  release.queue_provider:
    class: Crocos\Navy\DeployPlugin\Release\QueueProvider
    arguments:
      - %deploy.release.queue.config%

  release.command_context:
    class: Crocos\Navy\DeployPlugin\Release\CommandContext
    calls:
      - [ setEnv, [ %deploy.release.command.env% ] ]

  release.command_resolver:
    class: Crocos\Navy\DeployPlugin\Release\CommandResolver
    arguments:
      - @release.command_context
      - @shell
      - @service_container
      - @notifier
      - @logger

  release.command.anchor:
    class: Crocos\Navy\DeployPlugin\Release\Command\AnchorCommand
    arguments:
      - %deploy.release.command.lockfile%

  release.command.sail:
    class: Crocos\Navy\DeployPlugin\Release\Command\SailCommand
    arguments:
      - %deploy.release.command.lockfile%

  release.command.watch:
    class: Crocos\Navy\DeployPlugin\Release\Command\WatchCommand
    arguments:
      - %deploy.release.command.lockfile%

  release.worker:
    class: Crocos\Navy\DeployPlugin\Release\Worker
    arguments:
      - @release.queue
      - @release.controller
      - @logger


  # releaselog
  releaselog.branch_matcher:
    class: Navy\BranchMatcher
    arguments:
      - %deploy.releaselog.repository%

  releaselog.logger:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\Logger
    arguments:
      - @releaselog.logfile
      - @releaselog.period
      - @releaselog.markdown_scraper

  releaselog.logfile:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\LogFile
    arguments:
      - %deploy.releaselog.logger.config%

  releaselog.period:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\Period
    arguments:
      - ~

  releaselog.notifier:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\Notifier
    arguments:
      - @notifier
      - @release.command_context
      - @releaselog.markdown_scraper
      - %deploy.releaselog.notifier.config%

  releaselog.reader:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\Reader
    arguments:
      - @releaselog.logfile
      - @releaselog.period

  releaselog.markdown_scraper:
    class: Crocos\Navy\DeployPlugin\ReleaseLog\MarkdownScraper
